### ISSUE TITLE
Eclipse Issue Running R&R

### ISSUE THREAD

**Issue by gmur24** [watson-developer-cloud/retrieve-and-rank-java#16]
Please explain step 4. I cannot seem to figure it out.

![image](https://cloud.githubusercontent.com/assets/13022982/12209775/46faa0cc-b690-11e5-8814-cc58f4a6c2e3.png)

**Comment by germanattanasio** [comment]
@doconnor78 can you take a look at this ?

**Comment by doconnor78** [comment]
If you are developing against a local Liberty server then this step applies. Liberty will be installed to some location, e.g. on Windows c:/program files/websphere_liberty/... or on Mac /users/userName/websphere_liberty..
In step 4 ../LibertyRuntime refers to the install location of Websphere Liberty.. Once you navigate to the install location of Websphere Liberty there will be a 'usr' subfolder, and drilling down to that folder should reveal a 'servers' folder, and then within that there will be a folder whose name is the same as your Liberty server's name, but default 'defaultServer'

**Comment by germanattanasio** [comment]
Fixed with the new demo
