### ISSUE TITLE
[WARNING ] CLUSTER_ID, RANKER_ID and COLLECTION_NAME cannot be null

### ISSUE THREAD

**Issue by rlykins** [watson-developer-cloud/retrieve-and-rank-java#19]
I pulled the retrieve-and-rank-java github example, bound it to my retrieve-and-rank instance, and even updated the RetrieveAndRankResource.java file with my retrieve and rank information but when I submit a query I get the following warning in the logs.

[WARNING ] CLUSTER_ID, RANKER_ID and COLLECTION_NAME cannot be null

Is there some other task I need to perform to get this working properly?

I currently have a Bluemix ticket open, but they suggested that I submit this to Issues as well.

**Comment by germanattanasio** [comment]
Read the Step 8 and 9 in the [Getting Started](https://github.com/watson-developer-cloud/retrieve-and-rank-java#getting-started) instructions

**Comment by rlykins** [comment]
I said that I had already performed this though and have updated the user defined variables under environment variables.

I have followed the guide completely and still get this error.

**Comment by germanattanasio** [comment]
If you run it locally then make sure you update the following [variables](https://github.com/watson-developer-cloud/retrieve-and-rank-java/blob/master/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankResource.java#L71-L75)

**Comment by rlykins** [comment]
I'm pushing it live, but I had already updated those variables anyway.

Is there any other reason why I would be getting this error?
