### ISSUE TITLE
the demo URL does not work

### ISSUE THREAD

**Issue by ntodorov** [watson-developer-cloud/retrieve-and-rank-java#20]
The demo does not work. 
the URL http://retrieve-and-rank-demo.mybluemix.net/  that you have in the readme returns error:
_"The application or context root for this request has not been found: /"_

**Comment by germanattanasio** [comment]
Good catch. The link to the demo is http://retrieve-and-rank-demo.mybluemix.net/rnr-demo/dist/#/
I will be updating the demo with the link in the readme

**Comment by jsstylos** [comment]
@germanattanasio: It would be nice to add url guidelines to the demo guidelines
