### ISSUE TITLE
Result output different from cURL output

### ISSUE THREAD

**Issue by rlykins** [watson-developer-cloud/retrieve-and-rank-java#21]
I am currently using this code for my own collection and training set and I have been training it over the last couple weeks, but the output results have not seemed to improve. I compared the results from the webApp with results using cURL in the terminal and I am getting different responses. 

For example when using cURL it says 269 entries found for a question and it outputs the top 10 and scores them between 10-1. With the webApp I changed the code to to show the score and the top 3 responses have a score of 269, 268, and 267 and they are not the same top 3 responses, and actually the webApp responses are mostly inaccurate compared to the cURL responses. 

Is there something I need to change to output the top 3 ranked responses? Am I misunderstanding how this code is setup, does it put out the responses with the highest difference from the Solr responses? If I have misunderstood how the code works how would you recommend changing it to output the actual top 3 responses.

Thanks

**Comment by germanattanasio** [comment]
Are you using the ranker when using curl?

**Comment by rlykins** [comment]
Thanks for getting back to me, I realized what the issue was a few months
ago though. I had my webApp set to return 1000 lines vs. cURL returning
only 10.
