### ISSUE TITLE
Rank Status Failed

### ISSUE THREAD

**Issue by pranireddy9** [watson-developer-cloud/retrieve-and-rank-java#22]
Hi , 

I am developing the demo application of retrieve and rank for my organization and i am facing an interesting issue while i am creating a rank with the cranfield data csv file. Th rank is getting created and after some time ..its failing due to some data problem . I am using a java client to do so and i am completely using the cranfield data as my input to create a rank and i am using cranfield json data to post to my cluster. I am successful in each step except rank status is failing for some reason , can you please throw up any suggestions or any snippet where you can create a rank with the cranfield.

Here is the error 
```json
{
  "created": "2016-05-27T16:19:48.114-0500",
  "ranker_id": "3b140ax15-rank-2496",
  "name": "ranker2",
  "status": "Failed",
  "status_description": "Error encountered during training: Training data quality standards not met: invalid header (duplicate feature names). Row 1 of input data.",
  "url": "https://gateway.watsonplatform.net/retrieve-and-rank/api/v1/rankers/3b140ax15-rank-2496"
}
```

Thanks,
Pranitha.

**Comment by pranireddy9** [comment]
I have tried again today by starting all teh way from beginning and i have the same issue :+1: 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{
  "created": "2016-05-30T05:23:49.521-0500",
  "ranker_id": "3b140ax15-rank-2557",
  "name": "ranker2",
  "status": "Training",
  "status_description": "The ranker instance is in its training phase, not yet ready to accept rank requests",
  "url": "https://gateway.watsonplatform.net/retrieve-and-rank/api/v1/rankers/3b140ax15-rank-2557"
}
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: TRAINING
ranker status: FAILED

**Comment by germanattanasio** [comment]
This is not a problem of this repository. Seems that the service was having issues
