### ISSUE TITLE
How to use Retrieve and Rank without groundtruth

### ISSUE THREAD

**Issue by dpowell1** [watson-developer-cloud/retrieve-and-rank-java#26]
I manually trained the entire Retrieve and Rank service in Bluemix. How do I start the Java application without the groundtruth.json file?

**Comment by germanattanasio** [comment]
Hi @dpowell1 sorry for the delay. :sweat: I would recommend you to use the [Discovery service](https://www.ibm.com/watson/services/discovery/). I think you are already doing it actually 😝
