### ISSUE TITLE
Path should not include /rnr-demo/dist/#/

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/retrieve-and-rank-java#4]
Should be able to go to http://retrieve-and-rank-demo.mybluemix.net/ without being redirected to a different page (or getting a 404 error).

**Comment by germanattanasio** [comment]
This may help https://www.ng.bluemix.net/docs/#!starters/liberty/index.html#liberty

**Comment by germanattanasio** [comment]
Fixed with the latest changes and it's also backward compatible so the old link still work.[![selfie-0](http://i.imgur.com/hIQwn9D.gif)](https://github.com/thieman/github-selfies/)
