### ISSUE TITLE
Relative ranking numbers and icons not easily understandable

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/retrieve-and-rank-java#5]
The output contains a column with icons and numbers like (green up arrow) 3, (red down arrow) 2, without any description of what these represent. It'd be nice to have a hover text saying something like "Adding machine learning made this document appear 3 places higher in the results" or some other way for users to figure out what's going on.

**Comment by germanattanasio** [comment]
What message should I say? I can do the change real quick
